name: dtd_laptop_distribution_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
platforms:
  android:
  ios:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  # Flutter window webview
  webview_windows: ^0.2.2

  # Get assets path for window platform
  path: ^1.8.2
  # checking permissions
  permission_handler: ^10.2.0
  # toast popups
  fluttertoast: ^8.2.2
  # for camera
  camera: ^0.10.6
  cupertino_icons: ^1.0.2

  path_provider: ^2.0.9

  # Customizable dropdown button
  dropdown_button2: ^2.3.7
  # Helps to size down text for small screens
  auto_size_text: ^3.0.0
  geolocator: ^9.0.2

  #image compressor
  image_compression_flutter: ^1.0.4
  flutter_image_compress: ^2.1.0

  floating_action_bubble: ^1.1.4
  simple_speed_dial: ^0.1.7

  # login
  aad_oauth: ^1.0.1
  microsoft_graph_api: ^0.0.4

  http: ^1.0.0
  convert: ^3.1.1
  flutter_secure_storage: ^9.0.0

  #percentage bar
  percent_indicator: ^4.2.3
  flutter_screenutil: ^5.9.0

  #svg file
  flutter_svg: ^2.0.5

  #barcode
  mobile_scanner: 3.5.5

  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true  # Add this line



  # To add assets to your package, add an assets section, like this:
  assets:
    - lib/assets/strawberry-removebg-preview.png

    #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Regular.ttf

  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
